[package]
name = "tftst7735spi"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"

stm32f0xx-hal = { version = "0.18.0", features = ["stm32f072"] }
embedded-hal = "0.2.7"
st7735-lcd = "0.8.0"
embedded-graphics = "0.7"
