[package]
name = "blinkled"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "1.0.0"
stm32f0xx-hal = { version = "0.18", features = ["stm32f072", "rt"] }

[profile.release]
lto = true
codegen-units = 1